# fly.toml app configuration file generated for little-darkness-1565 on 2023-08-01T16:14:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-darkness-1565"
primary_region = "otp"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
